(() => {
  const state={filters:{from:"",to:"",brand:"all",store:"all",provider:"all",documentType:"all"}};
  const normalize=value=>String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase();
  const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  const money=value=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(Number(value)||0);
  const displayNumber=value=>new Intl.NumberFormat("es-CO").format(Number(value)||0);
  const blankFilters=()=>({from:"",to:"",brand:"all",store:"all",provider:"all",documentType:"all"});
  function amount(value){if(typeof value==="number")return value;const text=String(value??"").trim().replace(/[^\d,.-]/g,"");if(!text)return 0;if(/^[-]?\d{1,3}(\.\d{3})+(,\d+)?$/.test(text))return Number(text.replace(/\./g,"").replace(",","."))||0;if(/^[-]?\d{1,3}(,\d{3})+(\.\d+)?$/.test(text))return Number(text.replace(/,/g,""))||0;return Number(text.replace(",","."))||0;}
  function excelDate(value){if(typeof value==="number"&&value>30000)return new Date(Date.UTC(1899,11,30)+value*86400000).toISOString().slice(0,10);const text=String(value??"").trim(),match=text.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(match)return `${match[3]}-${match[2].padStart(2,"0")}-${match[1].padStart(2,"0")}`;const parsed=new Date(text);return text&&!Number.isNaN(parsed.getTime())?parsed.toISOString().slice(0,10):"";}
  function brandGroup(value){const key=normalize(value);if(key.includes("levi"))return "Levi's";if(key.includes("desigual"))return "Desigual";if(key.includes("wiseman"))return "Wiseman";return "Otros";}
  function rowsFromSheet(rows){if(rows.length<2)throw new Error("El archivo no contiene movimientos.");const headers=rows[0].map(normalize),required=["fecha","documento","tipo doc","concepto","proveedor","tienda","total","marca"];if(required.some(name=>!headers.includes(name)))throw new Error("El formato no contiene las columnas requeridas.");const get=(row,name)=>row[headers.indexOf(name)]??"";return rows.slice(1).filter(row=>row.some(cell=>cell!==""&&cell!==undefined)).map(row=>({date:excelDate(get(row,"fecha")),document:String(get(row,"documento")),documentType:String(get(row,"tipo doc")),concept:String(get(row,"concepto")),provider:String(get(row,"proveedor")||"Sin proveedor"),store:String(get(row,"tienda")||"Sin tienda"),brand:brandGroup(get(row,"marca")),total:amount(get(row,"total"))})).filter(row=>row.date||row.document||row.total);}
  const unique=field=>[...new Set((window.reportBudgetData||[]).map(row=>row[field]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"es"));
  function fillSelect(id,values,label){const select=document.querySelector(id);if(!select)return;const current=select.value;select.innerHTML=`<option value="all">${label}</option>${values.map(item=>`<option value="${escapeHtml(item)}">${escapeHtml(item)}</option>`).join("")}`;select.value=values.includes(current)?current:"all";}
  function hydrateFilters(){fillSelect("#budgetBrand",["Levi's","Desigual","Wiseman","Otros"].filter(item=>unique("brand").includes(item)),"Todas");fillSelect("#budgetStore",unique("store"),"Todas");fillSelect("#budgetProvider",unique("provider"),"Todos");fillSelect("#budgetDocumentType",unique("documentType"),"Todos");}
  function filteredData(){const f=state.filters;return(window.reportBudgetData||[]).filter(row=>(!f.from||row.date>=f.from)&&(!f.to||row.date<=f.to)&&(f.brand==="all"||row.brand===f.brand)&&(f.store==="all"||row.store===f.store)&&(f.provider==="all"||row.provider===f.provider)&&(f.documentType==="all"||row.documentType===f.documentType));}
  function aggregate(data,field){return[...data.reduce((map,row)=>map.set(row[field],(map.get(row[field])||0)+row.total),new Map())].sort((a,b)=>b[1]-a[1]);}
  function renderBars(id,entries,total){const target=document.querySelector(id);if(!target)return;if(!entries.length){target.innerHTML='<p class="empty-table">No hay movimientos para estos filtros.</p>';return;}const max=entries[0][1]||1;target.innerHTML=entries.map(([label,amount])=>`<div class="budget-bar"><div><span>${escapeHtml(label)}</span><b>${money(amount)}</b></div><i><em style="width:${Math.max(2,amount/max*100)}%"></em></i><small>${total?(amount/total*100).toLocaleString("es-CO",{maximumFractionDigits:1}):0}% del total</small></div>`).join("");}
  function render(){const data=filteredData(),total=data.reduce((sum,row)=>sum+row.total,0),providers=aggregate(data,"provider"),dates=data.map(row=>row.date).filter(Boolean).sort(),set=(id,text)=>{const node=document.querySelector(id);if(node)node.textContent=text;};set("#budgetTotal",money(total));set("#budgetMovements",displayNumber(data.length));set("#budgetAverage",data.length?money(total/data.length):"-");set("#budgetTopProvider",providers[0]?.[0]||"-");set("#budgetTopProviderValue",providers[0]?money(providers[0][1]):"Mayor ejecucion acumulada");set("#budgetPeriod",dates.length?`${new Date(dates[0]+"T00:00:00").toLocaleDateString("es-CO")} a ${new Date(dates.at(-1)+"T00:00:00").toLocaleDateString("es-CO")}`:"Sin movimientos para estos filtros");set("#budgetBrandCount",`${aggregate(data,"brand").length} categorias`);set("#budgetResultCount",`${displayNumber(data.length)} movimientos`);renderBars("#budgetBrandBars",aggregate(data,"brand"),total);renderBars("#budgetProviderBars",providers.slice(0,5),total);const body=document.querySelector("#budgetRows");if(body)body.innerHTML=data.length?data.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(row=>`<tr><td>${escapeHtml(row.date)}</td><td>${escapeHtml(row.document)}</td><td>${escapeHtml(row.concept)}</td><td>${escapeHtml(row.provider)}</td><td>${escapeHtml(row.store)}</td><td><span class="budget-brand">${escapeHtml(row.brand)}</span></td><td class="budget-amount">${money(row.total)}</td></tr>`).join(""):'<tr><td colspan="7" class="empty-table">No hay movimientos para estos filtros.</td></tr>';}
  function applySheet(sheet){window.reportBudgetData=rowsFromSheet(sheet);state.filters=blankFilters();hydrateFilters();render();const status=document.querySelector("#budgetImportStatus");if(status)status.textContent=`Presupuesto: ${displayNumber(window.reportBudgetData.length)} movimientos cargados.`;return window.reportBudgetData.length;}
  async function importBudget(file){const status=document.querySelector("#budgetImportStatus");if(status)status.textContent=`Leyendo ${file.name}...`;const files=await window.ReportImporter.unzip(await file.arrayBuffer()),workbook=window.ReportImporter.parseWorkbook(files);let loaded=0,lastError;for(const sheet of Object.values(workbook)){try{loaded=applySheet(sheet);if(loaded)break;}catch(error){lastError=error;}}if(!loaded)throw lastError||new Error("No se encontro una pestaña de ejecucion compatible.");window.saveReport?.(false);if(status)status.textContent=`Presupuesto: ${displayNumber(loaded)} movimientos cargados desde ${file.name}.`;window.showToast?.("Ejecucion de presupuesto actualizada");}
  function restoreData(data){window.reportBudgetData=Array.isArray(data)?data:[];hydrateFilters();render();}
  document.addEventListener("change",async event=>{if(event.target.matches("#importBudget")){const file=event.target.files?.[0];if(!file)return;try{await importBudget(file);}catch(error){console.error(error);const status=document.querySelector("#budgetImportStatus");if(status)status.textContent=`No se pudo cargar: ${error.message}`;window.showToast?.("No fue posible cargar el presupuesto");}finally{event.target.value="";}return;}const fields={budgetDateFrom:"from",budgetDateTo:"to",budgetBrand:"brand",budgetStore:"store",budgetProvider:"provider",budgetDocumentType:"documentType"};if(fields[event.target.id]){state.filters[fields[event.target.id]]=event.target.value;render();}});
  document.addEventListener("click",event=>{if(!event.target.closest("#budgetClearFilters"))return;state.filters=blankFilters();["budgetDateFrom","budgetDateTo"].forEach(id=>{const node=document.querySelector(`#${id}`);if(node)node.value="";});["budgetBrand","budgetStore","budgetProvider","budgetDocumentType"].forEach(id=>{const node=document.querySelector(`#${id}`);if(node)node.value="all";});render();});
  window.BudgetModule={importBudget,applySheet,restoreData,render};restoreData([]);
})();
